### ISSUE TITLE
סקירה ספרותית

### ISSUE THREAD

**Issue by shaykos** [Hofman2HQ/LLM_Antisemitism_FinalProject#1]
- [x] מאמר על בינה מלאכותית
- [x] מאמר על מודל זיהוי שפה
- [x] מאמר על אנטישמיות
- [x] מאמר על רשתות חברתיות והשימוש בהן
- [x] מאמר על אנטישמיות ברשת חברתית

**Comment by Hofman2HQ** [comment]
A developed solution for detecting hate speech "Hatescan" : 
https://www.diva-portal.org/smash/get/diva2:1784343/FULLTEXT01.pd

**Comment by Hofman2HQ** [comment]
Decision making involving big data with AI:
https://uobrep.openrepository.com/bitstream/handle/10547/623124/Artificial%20Intelligence%20in%20the%20era%20of%20Big%20Data%20revised%20final%20%281%29.pdf?sequence=2&isAllowed=n

**Comment by eliasihai** [comment]
Social Networking Sites: Their Users and Social
Implications — A Longitudinal Study

https://academic.oup.com/jcmc/article/17/4/467/4067681

PDF : 
https://dergipark.org.tr/en/download/article-file/252152

**Comment by Hofman2HQ** [comment]
@AcLior Add your articles here 👍

**Comment by eliasihai** [comment]
ANNOTATING ANTISEMITIC ONLINE CONTENT. TOWARDS AN APPLICABLE
DEFINITION OF ANTISEMITISM

https://arxiv.org/ftp/arxiv/papers/1910/1910.01214.pdf

**Comment by Hofman2HQ** [comment]
An introduction to NLP - Natural Language Processing.

https://academic.oup.com/jamia/article/18/5/544/829676?ref=https%3A%2F%2Fcodemonkey.link&login=false#31768894

**Comment by AcLior** [comment]
https://www.proquest.com/openview/0ea165c77d94139c11923ca33344ad6c/1?pq-origsite=gscholar&cbl=2026366&diss=y

שימוש ברשתות חברתיות

**Comment by AcLior** [comment]
מה זה אנטישמיות

https://books.google.co.il/books?hl=iw&lr=&id=pRY0CgAAQBAJ&oi=fnd&pg=PP1&dq=info:d--P-Mh6QAoJ:scholar.google.com/&ots=RvGNjyn5nk&sig=hAGAG4YgYbZB6go4LM3RgcIQYoM&redir_esc=y#v=onepage&q&f=false

**Comment by AcLior** [comment]
https://scholar.google.com/scholar?hl=iw&as_sdt=0%2C5&scioq=%D7%90%D7%A0%D7%98%D7%99%D7%A9%D7%9E%D7%99%D7%95%D7%AA+%D7%93%D7%95%D7%93+%D7%90%D7%A0%D7%92%D7%9C&q=antisemitism+and+social+media&oq=antisemitism+and+#d=gs_qabs&t=1706477246598&u=%23p%3Duv6619mhj8YJ

אנטישמיות ברשתות חברתיות

**Comment by shaykos** [comment]
מעולה. המאמרים מאושרים
